
import { Injectable } from '@angular/core';
import { Movie } from '../movie.model';

@Injectable({
  providedIn: 'root'
})
export class MovieService {

  getAllMovies(): Movie[] {
    return [
      {
        id: 1,
        title: 'Inception',
        genre: 'Sci-Fi',
        duration: 148,
        rating: 8.8,
        showtime: '2025-04-10T19:30:00',
        language: 'English',
        image: 'https://i.pinimg.com/originals/a6/cd/36/a6cd360aad592edcc110f3e9495b6d2a.jpg',
        location: 'Bangalore',
        theater: 'PVR Cinemas',
      },
      {
        id: 2,
        title: 'Vikram',
        genre: 'Action',
        duration: 174,
        rating: 8.3,
        showtime: '2025-04-10T21:00:00',
        language: 'Tamil',
        image: 'https://wallpapercave.com/wp/wp11049966.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 3,
        title: 'KGF: Chapter 2',
        genre: 'Action',
        duration: 168,
        rating: 8.5,
        showtime: '2025-04-11T20:00:00',
        language: 'Kannada',
        image: 'https://bollywoodlatestforu.com/wp-content/uploads/2021/01/KGF-chapter-2-budget-poster.jpg',
        location: 'Bangalore',
        theater: 'PVR Cinemas',
      },
      {
        id: 4,
        title: 'Bahubali',
        genre: 'Fantasy',
        duration: 159,
        rating: 8.1,
        showtime: '2025-04-12T19:00:00',
        language: 'Telugu',
        image: 'https://wallpapers.oneindia.com/ph-1024x768/2015/07/bahubali_143685159720.jpg',
        location: 'Mumbai',
        theater: 'PVR Cinemas',
      },
      {
        id: 5,
        title: 'Drishyam',
        genre: 'Drama',
        duration: 163,
        rating: 8.4,
        showtime: '2025-04-13T18:00:00',
        language: 'Malayalam',
        image: 'https://www.koimoi.com/wp-content/new-galleries/2022/05/ajay-devgns-drishyam-at-china-box-office-001.jpg',
        location: 'Coimbatore',
        theater: 'PVR Cinemas',
      },
      {
        id: 6,
        title: 'Dangal',
        genre: 'Biography',
        duration: 161,
        rating: 8.4,
        showtime: '2025-04-13T20:00:00',
        language: 'Hindi',
        image: 'https://s4.scoopwhoop.com/anj2/5de5fe1e50758d60a79f4fe2/957c9809-06be-49a5-9f15-bf36ba85e683.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 7,
        title: 'Avatar',
        genre: 'Adventure',
        duration: 162,
        rating: 7.9,
        showtime: '2025-04-14T22:00:00',
        language: 'English',
        image: 'https://cdna.artstation.com/p/assets/images/images/031/645/214/large/shreyas-raut-avatar-2.jpg?1604210989',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 8,
        title: 'Asuran',
        genre: 'Thriller',
        duration: 141,
        rating: 8.6,
        showtime: '2025-04-15T17:00:00',
        language: 'Tamil',
        image: 'http://onlookersmedia.in/wp-content/uploads/2019/01/asuran-first-look-poster-stills1.jpg',
        location: 'Delhi',
        theater: 'PVR Cinemas',
      },
      {
        id: 9,
        title: '777 Charlie',
        genre: 'Adventure',
        duration: 165,
        rating: 8.8,
        showtime: '2025-04-15T19:00:00',
        language: 'Kannada',
        image: 'https://assets.gadgets360cdn.com/pricee/assets/product/202205/777-Charlie-poster_1653245631.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 10,
        title: 'RRR',
        genre: 'Action',
        duration: 187,
        rating: 8.0,
        showtime: '2025-04-16T20:00:00',
        language: 'Telugu',
        image: 'https://wallpaperaccess.com/full/6222108.jpg',
        location: 'Pune',
        theater: 'PVR Cinemas',
      },
      {
        id: 11,
        title: 'Lucifer',
        genre: 'Drama',
        duration: 174,
        rating: 7.5,
        showtime: '2025-04-17T21:00:00',
        language: 'Malayalam',
        image: 'https://assets-in.bmscdn.com/discovery-catalog/events/et00019224-bjqazuwkfa-landscape.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 12,
        title: '3 Idiots',
        genre: 'Comedy',
        duration: 170,
        rating: 8.4,
        showtime: '2025-04-18T18:00:00',
        language: 'Hindi',
        image: 'https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2023/06/3-idiot-1688114504.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 13,
        title: 'The Batman',
        genre: 'Action',
        duration: 176,
        rating: 8.1,
        showtime: '2025-04-19T22:00:00',
        language: 'English',
        image: 'https://imgix.hoyts.com.au/mx/posters/nz/the-batman-7579058e.jpg',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      },
      {
        id: 14,
        title: 'Master',
        genre: 'Action',
        duration: 179,
        rating: 7.2,
        showtime: '2025-04-20T19:30:00',
        language: 'Tamil',
        image: 'https://wallpapercave.com/wp/wp8218847.jpg',
        location: 'Gujarat',
        theater: 'PVR Cinemas',
      },
      {
        id: 15,
        title: 'Kantara',
        genre: 'Mystery',
        duration: 150,
        rating: 8.9,
        showtime: '2025-04-21T20:30:00',
        language: 'Kannada',
        image: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/202210/Kantara_1_1200x768.jpeg?VersionId=cg8qm90nqeCXkGwEzydAKHyIh7KNrmCW',
        location: 'Chennai',
        theater: 'PVR Cinemas',
      }
    ];
  }

  getMovieById(id: number): Movie | undefined {
    return this.getAllMovies().find(movie => movie.id === id);
  }
}
